server:
  port: 9191

spring:
  application:
    name: API-GATEWAY    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/nemo/user/**
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/nemo/department/**
        
           

    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka      
  instance:
    hostname: localhost
   
     